language: ruby

services:
  - docker

script:
  docker build -t vpc-1 . 

after_success:
  echo "$DOCKER_ACCESSTOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push tlautens/vpc-docker-registry:vpc-1