language: ruby

services:
- docker

before_install:
 - echo "$DOCKER_ACCESSTOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1

script:
  docker build -t vpc-1 .

after_success:
  - docker push tlautens/vpc-docker-registry:vpc-1
